# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, these are base Go tasks!
  GOLANG_REPO_PATH: '{{.GOLANG_REPO_PATH | default "."}}'
  DEPGRAPH_ENTRY_POINT: '{{.GODEPGRAPH_ENTRY_POINT | default "main.go"}}'
  SPECIFIC_LINTER: '{{.SPECIFIC_LINTER | default ""}}'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  install-tools:
    cmds:
      # Install task and go externally. E.g via asdf. The needed versions for these should be pinned in the repo. E.g: In .tool-versions file.
      - go install golang.org/x/tools/gopls@v0.23.0
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
      - go install github.com/icholy/gomajor@v0.15.0
      - go install github.com/oligot/go-mod-upgrade@v0.12.0
      - go install github.com/kisielk/godepgraph@v1.0.0
      - go install github.com/ppipada/refdir@v0.7.1
      - go install github.com/vladopajic/go-test-coverage/v2@v2.19.0

  depgraph:
    cmds:
      - godepgraph -s -o {{.GOLANG_REPO_PATH}},command-line-arguments {{.GODEPGRAPH_ENTRY_POINT}} | dot -Tpng -o godepgraph.png


  upgrade-do:
    cmds:
      - go-mod-upgrade -v -f
      - go mod tidy

  upgrade-check:
    cmds:
      - gomajor list
      - go-mod-upgrade -l

  lint-gosort:
    cmds:
      - refdir ./...

  lint-gopls:
    vars:
      GO_FILES:
        sh: find {{.GOLANG_REPO_PATH | shellQuote}} -type f -name '*.go'
    cmds:
      - for:
          var: GO_FILES
        cmd: gopls check -- {{.ITEM | shellQuote}}

  lint-fix-specific:
    cmds:
      - golangci-lint run --fix --enable-only={{.SPECIFIC_LINTER}}

  lint:
    cmds:
      - golangci-lint run ./... -v

  test:
    cmds:
      # The count=1 is needed to disable test caching. this is so that coverage doesnt show stale data.
      # Issue: https://github.com/golang/go/issues/74873
      - go test -count=1 -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
      - go-test-coverage --config=./.testcoverage.yml

  lt:
    cmds:
      - task: lint
      - task: test
